In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('./data/PredictSavings2.csv')

In [3]:
df.head()

         DATE Forecastindicator       INCOME     EXPENSES
0  2020-09-01          Estimate  16140.40325  15528.86006
1  2020-08-01          Estimate  16140.40325  15528.86006
2  2020-07-01          Estimate  16140.40325  15528.86006
3  2020-06-01            Actual   8068.83000   9118.18000
4  2020-06-01            Actual   8068.83000   9118.18000

In [4]:
df = df.melt(id_vars=["DATE", "Forecastindicator"], 
        var_name="TYPE", 
        value_name="VALUE")

In [7]:
df.sort_values(['DATE', 'TYPE'], ascending=False, inplace=True)

In [9]:
df.head(10)

          DATE Forecastindicator      TYPE        VALUE
0   2020-09-01          Estimate    INCOME  16140.40325
49  2020-09-01          Estimate  EXPENSES  15528.86006
1   2020-08-01          Estimate    INCOME  16140.40325
50  2020-08-01          Estimate  EXPENSES  15528.86006
2   2020-07-01          Estimate    INCOME  16140.40325
51  2020-07-01          Estimate  EXPENSES  15528.86006
4   2020-06-01            Actual    INCOME   8068.83000
3   2020-06-01            Actual    INCOME   8068.83000
52  2020-06-01            Actual  EXPENSES   9118.18000
53  2020-06-01            Actual  EXPENSES   9118.18000

In [10]:
df.to_csv('./data/PredictSavings3.csv')

In [17]:
import pandas as pd

In [18]:
df = pd.read_csv('./data/PopularExpenses2.csv')
df.head()

        DATE    CLUSTER  VALUE
0  1/08/2018  Utilities      1
1  1/09/2018  Utilities      4
2  1/10/2018  Utilities      2
3  1/11/2018  Utilities      2
4  1/12/2018  Utilities      5

In [34]:
df2 = df.pivot_table('VALUE', ['DATE'], 'CLUSTER')
df2.fillna(0,inplace=True)
# df2.reset_index(inplace=True)
df2.sort_values('DATE', inplace=True, ascending=False)
# df3 = df2[['DATE', 'Auto & transport', 'Bottleshops', 'Cash Out', 'Chemists',
#        'Education', 'Entertainment', 'Fast food restaurants', 'Fees & charges',
#        'Gifts & donations', 'Grocery & supermarkets',
#        'Hotels, motels & resorts', 'Insurance', 'Investments', 'Loan Pay',
#        'Miscellaneous', 'Restaurants & dining', 'Retail Shopping',
#        'Subscription', 'Travel', 'Utilities']]
# df3.head(20)
df2.head(20)

CLUSTER,Auto & transport,Bottleshops,Cash Out,Chemists,Education,Entertainment,Fast food restaurants,Fees & charges,Gifts & donations,Grocery & supermarkets,"Hotels, motels & resorts",Insurance,Investments,Loan Pay,Miscellaneous,Restaurants & dining,Retail Shopping,Subscription,Travel,Utilities
DATE,,,,,,,,,,,,,,,,,,,,
1/12/2019,17.0,2.0,2.0,0.0,0.0,1.0,5.0,2.0,0.0,13.0,0.0,6.0,1.0,5.0,1.0,2.0,0.0,2.0,2.0,5.0
1/12/2018,19.0,2.0,4.0,1.0,1.0,0.0,9.0,2.0,1.0,30.0,0.0,4.0,2.0,5.0,3.0,2.0,6.0,2.0,1.0,5.0
1/11/2019,16.0,2.0,0.0,9.0,4.0,1.0,2.0,2.0,0.0,50.0,0.0,4.0,1.0,5.0,7.0,7.0,11.0,3.0,0.0,2.0
1/11/2018,30.0,1.0,3.0,3.0,3.0,0.0,9.0,3.0,1.0,49.0,0.0,4.0,2.0,4.0,1.0,5.0,4.0,3.0,1.0,2.0
1/10/2019,13.0,4.0,6.0,2.0,1.0,3.0,8.0,0.0,2.0,35.0,1.0,5.0,2.0,4.0,1.0,7.0,4.0,3.0,1.0,3.0
1/10/2018,13.0,0.0,5.0,0.0,3.0,3.0,10.0,3.0,1.0,45.0,0.0,5.0,2.0,5.0,1.0,4.0,6.0,2.0,0.0,2.0
1/09/2019,19.0,3.0,6.0,1.0,2.0,4.0,6.0,3.0,1.0,54.0,0.0,5.0,2.0,5.0,1.0,8.0,14.0,2.0,1.0,5.0
1/09/2018,22.0,2.0,5.0,1.0,4.0,0.0,18.0,2.0,1.0,49.0,0.0,3.0,1.0,4.0,0.0,3.0,10.0,2.0,1.0,4.0
1/08/2019,29.0,3.0,8.0,3.0,0.0,2.0,8.0,0.0,1.0,58.0,0.0,5.0,2.0,4.0,7.0,8.0,7.0,2.0,3.0,1.0
1/08/2018,17.0,0.0,4.0,1.0,2.0,1.0,4.0,2.0,0.0,31.0,2.0,1.0,1.0,4.0,2.0,2.0,5.0,3.0,0.0,1.0
1/07/2020,5.0,30.0,5.0,1.0,2.0,0.0,2.0,1.0,1.0,42.0,0.0,3.0,1.0,9.0,3.0,3.0,4.0,2.0,0.0,2.0
1/07/2019,31.0,0.0,2.0,4.0,5.0,1.0,5.0,0.0,0.0,44.0,0.0,5.0,3.0,5.0,5.0,9.0,11.0,4.0,0.0,4.0
1/06/2020,8.0,20.0,1.0,2.0,4.0,1.0,1.0,1.0,0.0,39.0,0.0,5.0,1.0,7.0,3.0,3.0,3.0,3.0,2.0,8.0
1/06/2019,24.0,0.0,2.0,0.0,1.0,1.0,4.0,0.0,3.0,45.0,0.0,2.0,5.0,4.0,2.0,7.0,8.0,3.0,0.0,5.0
1/05/2020,4.0,15.0,2.0,3.0,1.0,0.0,0.0,1.0,0.0,35.0,0.0,3.0,1.0,6.0,0.0,0.0,1.0,2.0,0.0,3.0
1/05/2019,28.0,1.0,3.0,0.0,6.0,0.0,3.0,3.0,1.0,55.0,0.0,4.0,3.0,4.0,3.0,5.0,6.0,4.0,0.0,3.0
1/04/2020,0.0,15.0,2.0,0.0,4.0,0.0,0.0,0.0,0.0,12.0,0.0,4.0,1.0,9.0,0.0,0.0,1.0,2.0,0.0,2.0
1/04/2019,26.0,0.0,4.0,3.0,1.0,2.0,4.0,2.0,1.0,47.0,0.0,5.0,2.0,5.0,3.0,7.0,8.0,3.0,0.0,2.0
1/03/2020,8.0,1.0,4.0,3.0,2.0,0.0,0.0,0.0,3.0,50.0,0.0,7.0,1.0,9.0,2.0,5.0,5.0,3.0,0.0,4.0
1/03/2019,32.0,1.0,6.0,1.0,2.0,2.0,8.0,3.0,1.0,50.0,1.0,4.0,3.0,5.0,2.0,7.0,10.0,2.0,0.0,4.0

In [36]:
df2.to_csv('PopularExpenses3.csv')